[STK-256] Go build and release
stakater/Jamadaar pull request #11
Opened 2018-06-06 09:00 UTC by faizanahmad055

2018-06-06 09:06 UTC, stakater-user commented
@faizanahmad055 Image is available for testing. ``docker pull stakater/jamadar:PR-11-1``

2018-06-11 08:23 UTC, stakater-user commented
@faizanahmad055 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.tools.stackator.com/job/Stakater/job/Jamadar/job/PR-11/2/) has Failed!

2018-06-11 08:34 UTC, stakater-user commented
@faizanahmad055 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.tools.stackator.com/job/Stakater/job/Jamadar/job/PR-11/3/) has Failed!

2018-06-11 08:45 UTC, stakater-user commented
@faizanahmad055 Image is available for testing. ``docker pull stakater/jamadar:PR-11-4``

2018-06-11 10:34 UTC, stakater-user commented
@faizanahmad055 Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.tools.stackator.com/job/Stakater/job/Jamadar/job/PR-11/5/) has Failed!

2018-06-11 11:07 UTC, stakater-user commented
@faizanahmad055 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins.tools.stackator.com/job/Stakater/job/Jamadar/job/PR-11/6/) has Failed!

2018-06-11 11:59 UTC, stakater-user commented
@faizanahmad055 Yikes! You better fix it before anyone else finds out! [Build 11](https://jenkins.tools.stackator.com/job/Stakater/job/Jamadar/job/PR-11/11/) has Failed!

2018-06-11 12:10 UTC, stakater-user commented
@faizanahmad055 Image is available for testing. ``docker pull stakater/jamadar:PR-11-12``

2018-06-12 05:30 UTC, hazim1093 requested changes

2018-06-12 05:30 UTC, hazim1093 commented on Jenkinsfile
> +@Library('github.com/stakater/fabric8-pipeline-library@goBuildAndRelease')
Use tag v2.4.0 instead of branch or master

2018-06-12 07:59 UTC, stakater-user commented
@faizanahmad055 Image is available for testing. ``docker pull stakater/jamadar:PR-11-13``

2018-06-12 08:00 UTC, hazim1093 approved these changes

2018-06-12 08:00 UTC, merged